repos:
  - repo: local
    hooks:
      - id: pc1
        name: pc1
        entry: bash -c "echo \"HELLO WORLD\" && exit 1"
        language: system
        pass_filenames: false
        verbose: true
        stages: [post-merge, post-rewrite, merge-commit]

default_language_version:
  python: python3.7